Update index.js
faceleg/node-pluploader pull request #7
Opened 2017-01-05 07:45 UTC by telvin

`fileData` is a blob, it does not contains the name property. I have added more property tmpFileName to be returned with the actual uploaded file name.

2017-01-05 19:42 UTC, faceleg commented
Why does the client need to know the temp file name?

2017-01-06 03:32 UTC, faceleg requested changes

2017-01-06 03:33 UTC, faceleg commented
So in the case of chunked uploads, the temporary file name as used on the server is required?

Could you post some code that explains why? Sorry I'm not trying to be difficult I just don't understand why the browser code would need to know the server temp file name

2017-01-06 04:02 UTC, telvin commented
I think I have looked at this in wrong direction because there was event `fileUploaded`, so any extra logic that I wanted should go in there instead of editing directly into module. 
I noticed that the returned name should be retrieved from `self.pendingUploads[fileIdentifier]` instead of reading from `fileData` from readFileAsync

2017-01-06 07:46 UTC, faceleg approved these changes

2017-01-06 07:46 UTC, merged